baseURL: "linus-holmberg.github.io"
title: Linus Holmberg
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

#social:
#  twitter: LinusHolmberg

taxonomies:
  tag: tags

menu:
  main:
    #- name: Projects
    #  url: /projects/
    #  weight: 1
    - name: Research
      url: /papers/
      weight: 2
    - name: Teaching
      url: /courses/
      weight: 3
    - name: News
      url: /news/
      weight: 4
    # - name: Archive
    #   url: /archive/
    #   weight: 5

params:
  description: "Hello! This is Linus! I'm a 2nd year Ph.D. student in Cognitive Science at Linköping University. My research interest is in the intersection of Human-AI Interaction, explanations, and something more. 
     Under the supervision of [Prof. Tom Ziemke](https://www.ziemke.se/), [Prof. Maria Riveiro](https://ju.se/en/personinfo?sign=RIVMAR), and [Assoc. Prof. Serge Thill](https://www.ru.nl/en/people/thill-s)."
  author: Linus Holmberg
  # googleAnalyticsID: ""
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Linus Holmberg
    subtitle: "Hello! This is Linus! I'm a 2nd year Ph.D. student in Cognitive Science at Linköping University. My research interest is in the intersection of Human-AI Interaction, explanations, and something more. 
     Under the supervision of [Prof. Tom Ziemke](https://www.ziemke.se/), [Prof. Maria Riveiro](https://ju.se/en/personinfo?sign=RIVMAR), and [Assoc. Prof. Serge Thill](https://www.ru.nl/en/people/thill-s). 

     <br><br>
     Write someting about me

     <br><br>
     Before coming to Linköping, 


     I am employed as a PhD student in Cognitive Science at Linköping University (LiU), Institution for Data Science (IDA), as a part of the cognition and interaction lab (COIN), having Prof. Tom Ziemke as my main supervisor. 

     However, the majority of my time is spent in the Jönköping AI Lab (JAIL), Jönköping Tekniska Högskola. There, I am doing research in the intersection of human-centered AI and explainable AI. My research contribute to the XPECT project, led by my other supervisor, Prof. Maria Riveiro, and is founded by Vetenskapsrådet.

     <br> <br>

     Thank you for visitng my webpage!
     "
    imageUrl: "/picture.jpeg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Linus Holmberg
    buttons:
      #- name: Projects
      #  url: /projects/
      - name: Research
        url: /papers/
      - name: Teaching
        url: /courses/
      - name: News
        url: /news/

  socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/linus-holmberg-2a7b5b239/"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=QHS0iYQAAAAJ&hl"
    #- name: GitHub
    #  url: "https://github.com/linus-holmberg"
    - name: Email
      url: "mailto:linus.holmberg@ju.se"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Linus Holmberg"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
